### ISSUE TITLE
Criar wireframes das telas mobile

### ISSUE THREAD

**Issue by tiepdjmm** [ti-eeepdjmm/website-eeep#2]
Com base na identidade visual do projeto crie as telas para a versão mobile do website.

**Comment by rickalves** [comment]
Telas criadas! Segue o projeto no figma! 

[Link](https://www.figma.com/design/oQPPKkoa3Bh1VVWE5Oaw7E/website-EEEPDJMM?node-id=0-1&t=tc3ovgH3rUgBu6Df-1)
